# Generated by Django 6.0.2 on 2026-02-06 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleStudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('curriculum', 'Curriculum'), ('workbook', 'Workbook'), ('leader_guide', 'Leader Guide'), ('video_series', 'Video Series'), ('devotional', 'Devotional'), ('other', 'Other')], default='other', max_length=30)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('scripture_focus', models.TextField(blank=True)),
                ('number_of_lessons', models.PositiveIntegerField(default=1)),
                ('duration_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='study_materials/covers/')),
                ('file', models.FileField(blank=True, null=True, upload_to='study_materials/files/')),
                ('external_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bible Study Material',
                'verbose_name_plural': 'Bible Study Materials',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SermonSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='sermons/series_covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sermon Series',
                'verbose_name_plural': 'Sermon Series',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('guest_speaker_name', models.CharField(blank=True, max_length=200)),
                ('guest_speaker_bio', models.TextField(blank=True)),
                ('primary_scripture_book', models.CharField(blank=True, choices=[('genesis', 'Genesis'), ('exodus', 'Exodus'), ('leviticus', 'Leviticus'), ('numbers', 'Numbers'), ('deuteronomy', 'Deuteronomy'), ('joshua', 'Joshua'), ('judges', 'Judges'), ('ruth', 'Ruth'), ('1_samuel', '1 Samuel'), ('2_samuel', '2 Samuel'), ('1_kings', '1 Kings'), ('2_kings', '2 Kings'), ('1_chronicles', '1 Chronicles'), ('2_chronicles', '2 Chronicles'), ('ezra', 'Ezra'), ('nehemiah', 'Nehemiah'), ('esther', 'Esther'), ('job', 'Job'), ('psalms', 'Psalms'), ('proverbs', 'Proverbs'), ('ecclesiastes', 'Ecclesiastes'), ('song_of_solomon', 'Song of Solomon'), ('isaiah', 'Isaiah'), ('jeremiah', 'Jeremiah'), ('lamentations', 'Lamentations'), ('ezekiel', 'Ezekiel'), ('daniel', 'Daniel'), ('hosea', 'Hosea'), ('joel', 'Joel'), ('amos', 'Amos'), ('obadiah', 'Obadiah'), ('jonah', 'Jonah'), ('micah', 'Micah'), ('nahum', 'Nahum'), ('habakkuk', 'Habakkuk'), ('zephaniah', 'Zephaniah'), ('haggai', 'Haggai'), ('zechariah', 'Zechariah'), ('malachi', 'Malachi'), ('matthew', 'Matthew'), ('mark', 'Mark'), ('luke', 'Luke'), ('john', 'John'), ('acts', 'Acts'), ('romans', 'Romans'), ('1_corinthians', '1 Corinthians'), ('2_corinthians', '2 Corinthians'), ('galatians', 'Galatians'), ('ephesians', 'Ephesians'), ('philippians', 'Philippians'), ('colossians', 'Colossians'), ('1_thessalonians', '1 Thessalonians'), ('2_thessalonians', '2 Thessalonians'), ('1_timothy', '1 Timothy'), ('2_timothy', '2 Timothy'), ('titus', 'Titus'), ('philemon', 'Philemon'), ('hebrews', 'Hebrews'), ('james', 'James'), ('1_peter', '1 Peter'), ('2_peter', '2 Peter'), ('1_john', '1 John'), ('2_john', '2 John'), ('3_john', '3 John'), ('jude', 'Jude'), ('revelation', 'Revelation')], max_length=30)),
                ('primary_scripture_chapter', models.PositiveIntegerField(blank=True, null=True)),
                ('primary_scripture_verse_start', models.PositiveIntegerField(blank=True, null=True)),
                ('primary_scripture_verse_end', models.PositiveIntegerField(blank=True, null=True)),
                ('additional_scriptures', models.TextField(blank=True, help_text='Additional scripture references')),
                ('summary', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True, help_text='Full sermon manuscript')),
                ('key_points', models.TextField(blank=True, help_text='Main points of the sermon')),
                ('notes', models.TextField(blank=True)),
                ('sermon_date', models.DateField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sermons/audio/')),
                ('audio_url', models.URLField(blank=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='sermons/video/')),
                ('video_url', models.URLField(blank=True)),
                ('video_embed_code', models.TextField(blank=True, help_text='YouTube/Vimeo embed code')),
                ('presentation_file', models.FileField(blank=True, null=True, upload_to='sermons/presentations/')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='sermons/thumbnails/')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('topics', models.CharField(blank=True, help_text='Comma-separated list of topics', max_length=500)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated list of tags', max_length=500)),
                ('recording_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='events.event')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_sermons', to='members.member')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons_preached', to='members.member')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='sermons.sermonseries')),
            ],
            options={
                'verbose_name': 'Sermon',
                'verbose_name_plural': 'Sermons',
                'ordering': ['-sermon_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SermonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note_type', models.CharField(choices=[('study_guide', 'Study Guide'), ('discussion_questions', 'Discussion Questions'), ('handout', 'Handout'), ('transcript', 'Transcript'), ('slides', 'Slides'), ('other', 'Other')], default='other', max_length=30)),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='sermons/notes/')),
                ('is_downloadable', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_notes', to='sermons.sermon')),
            ],
            options={
                'verbose_name': 'Sermon Note',
                'verbose_name_plural': 'Sermon Notes',
                'ordering': ['note_type', 'title'],
            },
        ),
    ]
