# Generated by Django 6.0.2 on 2026-02-06 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('service', 'Regular Service'), ('special', 'Special Program'), ('conference', 'Conference'), ('meeting', 'Meeting'), ('wedding', 'Wedding'), ('funeral', 'Funeral Service'), ('baptism', 'Baptism'), ('dedication', 'Child Dedication'), ('fellowship', 'Fellowship'), ('other', 'Other')], default='service', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(default='Main Sanctuary', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('is_online', models.BooleanField(default=False)),
                ('online_link', models.URLField(blank=True)),
                ('expected_attendees', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('requires_registration', models.BooleanField(default=False)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], max_length=50)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='events/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='members.member')),
                ('speakers', models.ManyToManyField(blank=True, related_name='speaking_events', to='members.member')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=200)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=17)),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('dietary_requirements', models.TextField(blank=True)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended')], default='pending', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='members.member')),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(blank=True, max_length=200)),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('visitor_phone', models.CharField(blank=True, max_length=17)),
                ('is_present', models.BooleanField(default=True)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to='members.member')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_attendances', to='members.member')),
            ],
            options={
                'verbose_name': 'Event Attendance',
                'verbose_name_plural': 'Event Attendances',
                'ordering': ['-check_in_time'],
                'unique_together': {('event', 'member')},
            },
        ),
    ]
