# Generated by Django 6.0.2 on 2026-02-06 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Occurrence',
                'verbose_name_plural': 'Event Occurrences',
                'ordering': ['occurrence_date', 'start_time'],
                'unique_together': {('event', 'occurrence_date')},
            },
        ),
        migrations.CreateModel(
            name='EventOccurrenceLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_occurrence_assignments', to='members.member')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_assignments', to='events.eventoccurrence')),
            ],
            options={
                'verbose_name': 'Event Occurrence Leader',
                'verbose_name_plural': 'Event Occurrence Leaders',
                'ordering': ['occurrence__occurrence_date', 'leader_name'],
            },
        ),
    ]
