# Generated by Django 6.0.2 on 2026-02-06 12:11

import django.db.models.deletion
from django.db import migrations, models


def migrate_occurrence_leader(apps, schema_editor):
    EventOccurrence = apps.get_model("events", "EventOccurrence")
    EventOccurrenceLeader = apps.get_model("events", "EventOccurrenceLeader")

    for occurrence in EventOccurrence.objects.all():
        assignment = (
            EventOccurrenceLeader.objects.filter(occurrence_id=occurrence.id)
            .exclude(member_id__isnull=True)
            .order_by("id")
            .first()
        )
        if assignment:
            occurrence.leader_id = assignment.member_id
            occurrence.save(update_fields=["leader"])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_recurrence_until_eventoccurrence_and_more'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoccurrence',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_occurrences_led', to='members.member'),
        ),
        migrations.RunPython(
            migrate_occurrence_leader,
            migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name='EventOccurrenceLeader',
        ),
    ]
