# Generated by Django 6.0.2 on 2026-02-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventoccurrence_leader_delete_eventoccurrenceleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence_weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Required for weekly/bi-weekly recurrence.', null=True),
        ),
    ]
