# Generated by Django 6.0.2 on 2026-02-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_recurrence_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_outline',
            field=models.TextField(blank=True),
        ),
    ]
