# Generated by Django 6.0.2 on 2026-02-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermfa',
            name='password_hash_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usermfa',
            name='require_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
