# Generated by Django 6.0.2 on 2026-02-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_seed_default_donation_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(
                choices=[('EUR', 'Euro'), ('USD', 'Dollar'), ('GBP', 'Pounds')],
                default='EUR',
                max_length=3,
            ),
        ),
    ]
